//footer.js
var footer = document.getElementById("footer");
var cfooter = config.footer;
var endfoot = document.createElement("div"); endfoot.setAttribute("class", "endfoot");
var ft_info = document.createElement("div"); ft_info.setAttribute("class", "ft-info f_l");
var ftlogo = document.createElement("div"); ftlogo.setAttribute("class", "ftlogo");
var ftlogoa = document.createElement("a");
var ftlogoaimg = document.createElement("img"); ftlogoaimg.src = cfooter.img;
ftlogoa.appendChild(ftlogoaimg);
ftlogo.appendChild(ftlogoa);
ft_info.appendChild(ftlogo);
var ft_title = document.createElement("div"); ft_title.setAttribute("class", "ft-title");
var ft_titlep = document.createElement("p"); ft_titlep.innerText = cfooter.descr;
ft_title.appendChild(ft_titlep);
ft_info.appendChild(ft_title);
endfoot.appendChild(ft_info);
var ft_list = document.createElement("div"); ft_list.setAttribute("class", "ft-list f_r");
var ft_nav = document.createElement("div"); ft_nav.setAttribute("class", "ft-nav");
var ft_nava = document.createElement("a"); ft_nava.href = ""; ft_nava.setAttribute("target", "_blank"); ft_nava.innerText = "关于我们";
var ft_nava2 = document.createElement("a"); ft_nava2.href = ""; ft_nava2.setAttribute("target", "_blank"); ft_nava2.innerText = "联系我们";
var ft_nava3 = document.createElement("a"); ft_nava3.href = ""; ft_nava3.setAttribute("target", "_blank"); ft_nava3.innerText = "版权声明";
var ft_nava4 = document.createElement("a"); ft_nava4.href = ""; ft_nava4.setAttribute("target", "_blank"); ft_nava4.innerText = "问题反馈";
var ft_nava5 = document.createElement("a"); ft_nava5.href = ""; ft_nava5.setAttribute("target", "_blank"); ft_nava5.innerText = "商务合作";
ft_nav.appendChild(ft_nava);
ft_nav.appendChild(ft_nava2);
ft_nav.appendChild(ft_nava3);
ft_nav.appendChild(ft_nava4);
ft_nav.appendChild(ft_nava5);
ft_list.appendChild(ft_nav);
var ft_copyright = document.createElement("p"); ft_copyright.innerText = cfooter.copyright; ft_copyright.setAttribute("class", "ft-copyright");
ft_list.appendChild(ft_copyright);
endfoot.appendChild(ft_list);
footer.appendChild(endfoot);
var tbox = document.createElement("div");
var tboxa = document.createElement("a"); tboxa.href = "/"; tboxa.setAttribute("id", "togbook");
var tboxa2 = document.createElement("a"); tboxa2.href = "javascript:void(0)"; tboxa.setAttribute("id", "gotop");
tbox.appendChild(tboxa);
tbox.appendChild(tboxa2);
footer.appendChild(tbox);